# https://stackoverflow.com/questions/62432961/how-to-use-nodeport-with-kind
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    # extraPortMappings:
    #   - containerPort: 80
    #     hostPort: 80
    #     listenAddress: "10.0.0.35"
    #     protocol: TCP
    #   - containerPort: 443
    #     hostPort: 443
    #     listenAddress: "10.0.0.35"
    #     protocol: TCP
