apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: linux-bridge-net-ipam
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "macvlan",
    "master": "eth1",
    "mode": "bridge",
    "ipam": {
    "type": "host-local",
    "ranges": [
    [ {
    "subnet": "12.10.0.0/16",
    "rangeStart": "12.10.1.20",
    "rangeEnd": "12.10.3.50"
    } ]
    ]
    }
    }'
